### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#1]
I've put a basic explanation of what we're trying to do in the README, but it could probably use some improvement. In particular, we should add a copyright/disclaimer to it like the one Phil showed me.

**Comment by drphilmarshall** [comment]
I'm on the case! Can you assign me, please? Thanks!

**Comment by tholoien** [comment]
Hi Phil, looks like I need you to accept the invite to collaborate for me to be able to assign you to the issue. (It's only giving me the option of assigning myself.)

**Comment by drphilmarshall** [comment]
Ah yes! Just accepted. Self-assigning, then closing :-)

**Comment by drphilmarshall** [comment]
See #6 for the addition.
