### ISSUE TITLE
K-correction

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#14]
Switch the K-correction for the host magnitudes from the [K-Correction Calculator](http://kcor.sai.msu.ru/) code to [kcorrect](https://github.com/astropy/kcorrect). This should let us get colors for the higher redshift galaxies.

**Comment by drphilmarshall** [comment]
Nice!

**Comment by tholoien** [comment]
This has been implemented. The new '_master.csv' data files have K-corrected AB magnitudes for the host magnitudes.

**Comment by drphilmarshall** [comment]
This kind of data munging is the good fight, Tom. Well done :-)
