### ISSUE TITLE
XDGMM Class

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#15]
Create XDGMM class that incorporates the astroML and Bovy et al. fitting methods and is a wrapper for the scikit-learn Estimator class so that it can be used with the scikit-learn machine learning (cross validation) methods.

**Comment by tholoien** [comment]
This is under construction and can be found [here](https://github.com/tholoien/XDGMM)

**Comment by drphilmarshall** [comment]
This looks like an epic to me, in the sense that there are several smaller steps along the path to a good, re-useable XDGMM class that could be spun off into its own package. I'd suggest sub-issues as follows, see what you think: 1) Start wrapper class in rough scikit-learn style to reproduce astroML results, 2) Add and test method to condition on the host parameters, 3) adapt to enable it to be called from a scikit learn CV object, 4) export to a new package. Or something like that - I chose the order to reflect your priorities but I may not have them quite right. When you're ready, you could add a checklist to the first comment in this thread and then make an issue for each sub-task. What do you think?

**Comment by drphilmarshall** [comment]
PS. It'll be no problem that this issue would be an epic that was itself contained within the "Master Plan" epic :-)

**Comment by drphilmarshall** [comment]
Excellent! At what point will you consider this issue closeable?

**Comment by tholoien** [comment]
I am going to close it when I have a class that can be used for the scikit-learn methods, has correct conditioning, and implements at least one of the methods for XDGMM. All that is left at this point is fixing up the conditioning.

**Comment by drphilmarshall** [comment]
Oh cool - really glad that the scikit-learn machinery now works! Can you
push a simple Demo.ipynb notebook that shows this in action?

**Comment by tholoien** [comment]
XDGMM is [up and running](https://github.com/tholoien/XDGMM). Closing this.

**Comment by drphilmarshall** [comment]
Yesss! Nice work, Tom :-)
