### ISSUE TITLE
Setup unit testing and Travis CI

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#17]
This will be useful for making sure the code is working and so other people can download and use it.

**Comment by tholoien** [comment]
This is setup, but Travis needs to be able to install the XDGMM to work. Does anyone have an example of this functionality?

**Comment by drphilmarshall** [comment]
My starting point would be to add the following line to the end of the
`requirements.txt` file:

```
git+git://github.com/tholoien/XDGMM.git#egg=xdgmm
```

I learned this while working with Milan on `SLTimer`, which requires `PyCS`
- if the above line doesn't work straight away, we should go see what
  `PyCS` is doing with this "egg" business. It's to do with the `setup.py` I
  think.

**Comment by tholoien** [comment]
Got it working. Just had to add the equivalent line for xdgmm to the .travis.yml and make sure the XDGMM dependencies were installed first.

Unit testing is up and running and the build is passing.

**Comment by drphilmarshall** [comment]
Rock. On.
