### ISSUE TITLE
SDSS Supernovae

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#2]
It looks like SDSS should have a fairly large catalog of supernovae and host galaxies, based on Sako et al. (2014): http://arxiv.org/abs/1401.3317

However, the catalog website linked off the arXiv page (http://sdssdp62.fnal.gov/sdsssn/DataRelease/index.html) appears to be down, so I'm not sure how to access the full catalog information. 

I've sent Sako an email asking him about it, but have yet to hear a response. Does anyone else have a suggestion for others to talk to or another way to access the data?

**Comment by tholoien** [comment]
I have found the SDSS catalog (data.sdss3.org/sas/dr10/boss/papers/supernova) and retrieved the info we needed.

**Comment by drphilmarshall** [comment]
Like a BOSS
