### ISSUE TITLE
TravisCI demo failure

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#24]
Hi Phil, 

Looks like TravisCI is failing when it gets to the step of running the demo notebook. Looks like it's maybe a problem with jupyter on Travis? Could you take a look?

Thanks.

**Comment by drphilmarshall** [comment]
Build is now passing: https://travis-ci.org/tholoien/empiriciSN/builds/165303665

Key was to specify the python kernel when running jupyter in an anaconda environment, like this:

```
jupyter nbconvert --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=600 --to notebook --execute Notebooks/Demo.ipynb
```

Sorry about that!
