### ISSUE TITLE
Including Error in sampling from conditionals

### ISSUE THREAD

**Issue by jbkalmbach** [tholoien/empiriciSN#25]
While adapting the empiricSN demo notebook for use in Twinkles (see issue [ #310](DarkEnergyScienceCollaboration/Twinkles#310)). I noticed that including error in sampling from the conditional distribution was not working. I have found the bug and will submit a pull request.

**Comment by tholoien** [comment]
Thanks for finding and fixing that bug. Pull Request has been merged, so I'm closing this.
