### ISSUE TITLE
SALT2 Parameters for SNLS SNe

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#7]
I found a more recent set of light curve parameters for the SNLS supernovae that fit the light curves with SALT2 instead of SALT, which I had before. I was previously converting the SDSS SALT2 parameters into SALT ones to fit the SNLS data, but I think it will be better to just grab these SALT2 fits for the SNLS supernovae and have everything using those parameters. Simulation code like sncosmo should be able to produce light curves using only the SALT2 stretch and color parameters and the redshift, so no peak mag will be needed.

Creating this to track the gathering of the SALT2 data.

**Comment by tholoien** [comment]
I retrieved the SALT2 parameters for the SNLS sample from the [Betoule et al. (2014)](http://adsabs.harvard.edu/abs/2014yCat..35680022B) catalog. 

Since the catalog provides peak rest-frame m_B, x1, and c, I used sncosmo to get x0 based on these parameters. Since the model doesn't incorporate uncertainties in the parameters, I perturbed the input values and produced 1000 values of x0, then used the x0 distribution to get a median value for x0 and an estimate of the uncertainty.

**Comment by drphilmarshall** [comment]
Excellent!

**Comment by tholoien** [comment]
After plotting the new results, there is a systematic offset between the x0 parameters for the SNLS supernovae (which I calculated) and the x0 parameters for the SDSS supernovae, which were given in the catalogs. I am assuming this is an error that I made, as the two samples match nicely in the x1 and c parameters, so I am reopening this issue while I try to figure out where I went wrong.

**Comment by tholoien** [comment]
Okay, after discussing with one of the sncosmos authors, it seems I have been doing things correctly, and that the x0 distributions shouldn't match, since x0 captures apparent brightness. Since the SNLS supernovae are fainter, they should have smaller x0 values. Closing this again.
